[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "server/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  autoLaunch = false
  framework = "#custom"
